// constants/clothingData.ts

export const CLOTHING_ITEMS = [
  {
    id: 1,
    name: 'Punk Oversized Hoodie',
    price: 89.99,
    originalPrice: null,
    category: 'Hoodies',
    image: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?auto=format&fit=crop&w=600&q=80',
    description: 'Oversized fit with distressed details',
    isBestSeller: true,
    isOnSale: false,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 2,
    name: 'Y2K Graphic Tee',
    price: 45.99,
    originalPrice: 65.99,
    category: 'T-Shirts',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=80',
    description: 'Vintage 2000s aesthetic print',
    isOnSale: true,
    isBestSeller: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: 3,
    name: 'Cargo Pants Black',
    price: 79.99,
    originalPrice: null,
    category: 'Pants',
    image: 'https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?auto=format&fit=crop&w=600&q=80',
    description: 'Multiple pockets, relaxed fit',
    isBestSeller: true,
    isOnSale: false,
    sizes: ['28', '30', '32', '34', '36'],
  },
  {
    id: 4,
    name: 'Street Style Sneakers',
    price: 129.99,
    originalPrice: null,
    category: 'Sneakers',
    image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=600&q=80',
    description: 'Premium leather high-tops',
    isBestSeller: false,
    isOnSale: false,
    sizes: ['7', '8', '9', '10', '11', '12'],
  },
  {
    id: 5,
    name: 'Punk Chain Belt',
    price: 34.99,
    originalPrice: 49.99,
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=600&q=80',
    description: 'Metal chain with custom clasp',
    isOnSale: true,
    isBestSeller: false,
    sizes: ['One Size'],
  },
  {
    id: 6,
    name: 'Grunge Denim Jacket',
    price: 99.99,
    originalPrice: 139.99,
    category: 'Jackets',
    image: 'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?auto=format&fit=crop&w=600&q=80',
    description: 'Distressed with patches',
    isOnSale: true,
    isBestSeller: true,
    sizes: ['S', 'M', 'L', 'XL'],
  },
];

export const CATEGORIES = ['All', 'Hoodies', 'T-Shirts', 'Pants', 'Jackets', 'Sneakers', 'Accessories'];